// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSP.Domain.Entities;

public partial class Discount
{
    public int OrderDiscountId { get; set; }

    public int OrderId { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public string DiscountedBy { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Order Order { get; set; }
}