// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CSP.Domain.Entities;

public partial class Expense
{
    public int ExpensesId { get; set; }

    public int? OrderId { get; set; }

    public string Description { get; set; }

    public DateTime SpendDate { get; set; }

    public bool IsCompanyExpenses { get; set; }

    public decimal Amount { get; set; }

    public string PaidBy { get; set; }

    [JsonIgnore]
    public virtual Order Order { get; set; }
}