// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSP.Domain.Entities;

public partial class Order
{
    public int OrderId { get; set; }

    public string OrderName { get; set; }

    public DateTime? OrderDate { get; set; }

    public decimal TotalAmount { get; set; } = 0;

    public string Note { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsOpen { get; set; }

    public decimal PaidAmount { get; set; } = 0;

    public decimal TotalDiscount { get; set; } = 0;

    public decimal TotalBalance { get; set; } = 0;
    public decimal TotalExpenses { get; set; } = 0;

    public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    //public int OrderId { get; set; }

    //public string OrderName { get; set; }

    //public DateTime? OrderDate { get; set; }

    //public decimal TotalAmount { get; set; }

    //public string Note { get; set; }

    //public string CreatedBy { get; set; }

    //public string UpdatedBy { get; set; }

    //public string DeletedBy { get; set; }

    //public bool? IsDeleted { get; set; } 

    //public bool? IsOpen { get; set; }

    //public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();

    //public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    //public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    //public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}