// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSP.Domain.Entities;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int OrderId { get; set; }

    public DateTime PaymentDate { get; set; }

    public string PayerName { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public bool IsDeleted { get; set; } = false;

    public decimal Amount { get; set; }

    public string PayTo { get; set; }

    public virtual Order Order { get; set; }
}